version: '3'

services:
  webserver:
    image: nginx:alpine
    volumes:
      - ../map/:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=decarbnow.space
    networks:
      - revproxy
  streamer:
    build: ../map/streamer
    volumes:
      - ../map/data:/usr/src/app

networks:
  revproxy:
    external: true
